### PR TITLE
Solved issue regarding the addition and deletion of medicine,test row in form.html

### PR DESCRIPTION
**Pull request by sanchit-sinha**
Updated form.html and logic for updating and deleting rows of medicine and test
image

### CODE REVIEW

**Comment by shoryak** [comment]
If i am leaving any numerical field of fees and submitting the form the app crashes , can you try to fix this issue , either by making them a required field or by any other means , it gives a wrong impression that the app is not in working condition hence it is a high priority to fix this.

**Comment by phoenix-23** [comment]
when no. of medicines or/and tests are entered as 0, the form does not submit... I think that needs to be changed

**Comment by phoenix-23** [comment]
for the issue, pointed out by @shoryak, I think a default value can be provided in the js corresponding to the input fields... Basically, when we are leaving the fees value blank, the null value passed is crashing the site. Making it a "compulsory numeric" input field can solve the issue. If not resolved, it can be checked in the js before passing to the backend and a default value (like 0) can be sent when the field is left blank.

**Comment by sanchit-sinha** [comment]
Made the required changes !

**Comment by shoryak** [comment]
> Made the required changes !

Yes all the issues regarding this has been resolved , the  PR seems ready to merge

**Pull request merged**
