### PR TITLE
Added role based restriction and manually tested login functionality 

### LINKED ISSUE #25: adding role based restriction in login system
I am currently working on it !

### PR DESCRIPTION
**Pull request by sanchit-sinha**
Fixes: 
* updated message displayed when user tries to log-in with invalid credentials 
* updated the logic to allow correct user to view the dashboard
* fixed bugs and restricted pages to their respective roles
* stored test-login-data in ``login.json`` and superuserdata in ``superuser.json`` in ``dummyData``

closes #25

### CODE REVIEW

**Comment by sanchit-sinha** [comment]
You may loaddata from ``login.json`` to test users(given ``username = password``) after creating the ``superuser``

**Comment by sanchit-sinha** [comment]
@phoenix-23 Kindly resolve the conflict after #27 is merged. After that I'll do the same for #29

**Comment by sanchit-sinha** [comment]
Resolved conflicts!

**Comment by shoryak** [comment]
It seems fine to me , some minor issues that i noted unrelated to this pr ,
> Rollnumber is asking for exactly 6 digits in admin signup for doctor/admin and message of getting account created is displayed in red in adminsignup.

Pr seems to ready to merge.

**Review by phoenix-23 — APPROVED** [review]
All updates and fixes seem fine and bug-free to me too.

**Review by shoryak — APPROVED** [review]

**Pull request merged**
