### PR TITLE
Added file adding system to database and file viewing in frontend

### PR DESCRIPTION
**Pull request by phoenix-23**
As discussed earlier, I have added the `FileField` attribute in the `Form` object and made necessary changes in all dashboard frontends (and corresponding backend edits) to view the file.
Currently, there is no mapping of the "Attach Receipts" input field in the "New Form" option to the added `FileField`. Hence, currently, we have to fill out the form and then click on submit. It will show an error. Simply go to admin without disturbing anything else and add a file from admin in that demo form. Then reload the error page, and the patient dashboard reloads fine. You can view the document uploaded by clicking on the "View Document" option in the "View Form" and "View Request" pop-ups for all dashboards.

Next step in this regard would be to map the "file upload" in the "New Form" option to this `FileField` attribute in the form table. @sanchit-sinha @atreya221 please look into this.

### CODE REVIEW

**Comment by sanchit-sinha** [comment]
I am unable to view the uploaded file using the "View Document" option in the "View Form" and "View Request" pop-ups.

You can save save the file in database on clicking the submit button by making the following changes :
1) in ``form.html``


2) in ``views.py``


Please try it out

**Comment by Gaukm01** [comment]
View Document is working fine after adding a document from admin as mentioned. One suggestion, it would be better if the **view document** open the document in new tab. Can refer to this : https://stackoverflow.com/questions/5415600/how-to-open-url-in-new-tab-from-django. 
Apart from this is the issue of properly showing HC Medical Advisior name correctly in the View Transaction fixed in a different PR?

**Comment by phoenix-23** [comment]
@sanchit-sinha I have added the snippets of code you asked. Now it is taking the file from the form and storing it in the database as required. Thanks !

**Comment by phoenix-23** [comment]
@Gaukm01 I went over the solution in the link provided by you. The solution mentioned there are for backends where we are rendering a separate HTML page to display the pdf, which we are not doing in our backend. Instead, we are using some in-built functions to open the pdf. And for them the mentioned solutions won't work. I am looking for any documentation for the said in-built functions. But till I find any, I think we can proceed further by merging this PR.
(Also many people suggested that opening files in new tabs are quite troublesome for users, which is true as you cannot go back, instead you would have to close the tab to get back to the portal page)

**Comment by phoenix-23** [comment]
@Gaukm01 file opening in new tabs has been added
@sanchit-sinha can you please resolve the merge conflicts. I am unable to gauge the right components and don't want to undo your work. Thanks !

**Comment by sanchit-sinha** [comment]
[phoenix-23](https://github.com/phoenix-23) Kindly resolve the conflict after https://github.com/shoryak/hc_reimbursement/pull/27 is merged. After that I'll do the same for https://github.com/shoryak/hc_reimbursement/pull/29

**Comment by sanchit-sinha** [comment]
> @Gaukm01 file opening in new tabs has been added @sanchit-sinha can you please resolve the merge conflicts. I am unable to gauge the right components and don't want to undo your work. Thanks !

Ok I'll will look into it

**Comment by Gaukm01** [comment]
> @Gaukm01 Yes, that string display issue was resolved in #20. In which part are you still facing this issue ?

I wanted to ask this display issue only. If it's fixed then it's good.

**Comment by sanchit-sinha** [comment]
@phoenix-23 Kindly look into https://github.com/phoenix-23/hc_reimbursement/pull/1. I have resolved the conflict and added ``required`` parameter in ``<input> tag for file`` to prevent the page from crashing on form submission!

**Pull request merged**
