### PR TITLE
repeated email crashing  bug fixed in adminsignup

### PR DESCRIPTION
**Pull request by shoryak**
#26 fixed

### CODE REVIEW

**Review by phoenix-23 — APPROVED** [review]

**Comment by phoenix-23** [comment]
Basically, we need to add the block of code (which you added) for every field which has the property `unique=True` in both patientl sign up and admin signup

**Comment by shoryak** [comment]
> Basically, we need to add the block of code (which you added) for every field which has the property `unique=True` in both patientl sign up and admin signup

Yes , correct . We have added it for username , email and roll number . DO we need it for anything else ?

**Comment by phoenix-23** [comment]
In my opinion that would be all.

**Review by sanchit-sinha — APPROVED** [review]

**Comment by shoryak** [comment]
> In my opinion that would be all.

Name could be same na ?

**Comment by phoenix-23** [comment]
Yes name can be same

**Comment by sanchit-sinha** [comment]
This seems fine to me. It can be merged imo

**Pull request merged**
